export const auditTableData = [
  {
    description: 'User logged out',
    username: 'john_doe',
    userType: 'Admin',
    auditDuration: '2 hours',
    category: 'Security',
    action: 'Logged Out',
  },
  {
    description: 'user logged in',
    username: 'jane_smith',
    userType: 'User',
    auditDuration: '1 hour',
    category: 'Compliance',
    action: 'Logged in',
  },
  {
    description: 'User logged in',
    username: 'alice_wonderland',
    userType: 'Admin',
    auditDuration: '3 hours',
    category: 'Security',
    action: 'Logged In',
  },
  {
    description: 'Ut enim ad minim veniam',
    username: 'bob_jones',
    userType: 'system',
    auditDuration: '2.5 hours',
    category: 'Compliance',
    action: 'Fetched',
  },
  {
    description: 'Quis nostrud exercitation ullamco',
    username: 'mary_smith',
    userType: 'Admin',
    auditDuration: '1.5 hours',
    category: 'Security',
    action: 'Viewed',
  },
  {
    description: 'Duis aute irure dolor in reprehenderit',
    username: 'sam_adams',
    userType: 'system',
    auditDuration: '2 hours',
    category: 'Compliance',
    action: 'Fetched',
  },
  {
    description: 'Excepteur sint occaecat cupidatat non proident',
    username: 'emma_doe',
    userType: 'Admin',
    auditDuration: '2 hours',
    category: 'Security',
    action: 'Logged Out',
  },
  {
    description: 'Sunt in culpa qui officia deserunt',
    username: 'joe_smith',
    userType: 'User',
    auditDuration: '3 hours',
    category: 'Compliance',
    action: 'Fetched',
  },
  {
    description: 'Nemo enim ipsam voluptatem quia',
    username: 'alex_jones',
    userType: 'Admin',
    auditDuration: '1 hour',
    category: 'Security',
    action: 'Viewed',
  },
  {
    description: 'Neque porro quisquam est qui dolorem ipsum',
    username: 'sara_adams',
    userType: 'User',
    auditDuration: '2 hours',
    category: 'Compliance',
    action: 'Logged In',
  },
  {
    description: 'Neque porro quisquam est qui dolorem ipsum',
    username: 'sara_adams',
    userType: 'User',
    auditDuration: '2 hours',
    category: 'Compliance',
    action: 'Logged In',
  },
  {
    description: 'Neque porro quisquam est qui dolorem ipsum',
    username: 'sara_adams',
    userType: 'User',
    auditDuration: '2 hours',
    category: 'Compliance',
    action: 'Logged In',
  },
  {
    description: 'Neque porro quisquam est qui dolorem ipsum',
    username: 'sara_adams',
    userType: 'User',
    auditDuration: '2 hours',
    category: 'Compliance',
    action: 'Logged In',
  },
  {
    description: 'Neque porro quisquam est qui dolorem ipsum',
    username: 'sara_adams',
    userType: 'User',
    auditDuration: '2 hours',
    category: 'Compliance',
    action: 'Logged In',
  },
  {
    description: 'Neque porro quisquam est qui dolorem ipsum',
    username: 'sara_adams',
    userType: 'User',
    auditDuration: '2 hours',
    category: 'Compliance',
    action: 'Logged In',
  },
];
