import { Icon } from '@iconify/react';

export const countries = [
  {
    name: 'Afghanistan',
    code: 'AF',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Albania',
    code: 'AL',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Algeria',
    code: 'DZ',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Andorra',
    code: 'AD',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Angola',
    code: 'AO',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Antigua',
    code: 'AG',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Argentina',
    code: 'AR',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Armenia',
    code: 'AM',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Australia',
    code: 'AU',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Austria',
    code: 'AT',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Bahamas',
    code: 'BS',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Bahrain',
    code: 'BH',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Barbados',
    code: 'BB',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Belarus',
    code: 'BY',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Belgium',
    code: 'BE',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Belize',
    code: 'BZ',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Benin',
    code: 'BJ',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
  {
    name: 'Bhutan',
    code: 'BT',
    id: <Icon icon="f7:rectangle-on-rectangle" />,
    passport: <Icon icon="openmoji:cross-mark" />,
    license: <Icon icon="mynaui:rectangle" />,
    permit: <Icon icon="openmoji:cross-mark" />,
  },
];
